create table tb_role
(
    id        bigint generated by default as identity,
    authority varchar(255),
    primary key (id)
);

create table tb_user_role
(
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);

create table tb_users
(
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id         bigint generated by default as identity,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    email      varchar(255) unique,
    img_url    varchar(255),
    name       varchar(255),
    password   varchar(255),
    primary key (id)
);

alter table if exists tb_user_role
    add constraint FKea2ootw6b6bb0xt3ptl28bymv
        foreign key (role_id)
            references tb_role;

alter table if exists tb_user_role
    add constraint FKpn4njnr07hiiam9pg4pp3xan7
        foreign key (user_id)
            references tb_users;